# -*- coding: utf-8 -*-
"""FireDetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18uwE__eKjfonh5lpgKKwfKyicOTCDzUd
"""

#!pip install ultralytics

import zipfile
import os

zip_file = '/content/drive/MyDrive/archive.zip'
output_dir = 'data'

os.makedirs(output_dir, exist_ok=True)

with zipfile.ZipFile(zip_file, 'r') as zip_ref:
    zip_ref.extractall(output_dir)

from ultralytics import YOLO

model = YOLO('yolov8n.pt')

# Train the model
results = model.train(data='/content/data/data.yaml', epochs=10, imgsz=640)

import zipfile
import os

def zip_folder(folder_path, output_path):
    with zipfile.ZipFile(output_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for root, dirs, files in os.walk(folder_path):
            for file in files:
                zipf.write(os.path.join(root, file), os.path.relpath(os.path.join(root, file), folder_path))

# Replace '/content/runs' with the path to your folder
folder_path = '/content/runs'
# Replace '/content/hehe.zip' with the desired output path and filename
output_path = '/content/hehe.zip'

zip_folder(folder_path, output_path)